#!/bin/bash
echo -n "## " > TEST.md
pwd | rev | cut -d/ -f1 | rev | tr '_' ' ' | tr [:lower:] [:upper:] >> TEST.md
ls -1 | sort -h | cat -E | nl -s":%* [" | cut -d: -f2- | tr "$" "]" | tr "%" "\n" >> TEST.md
