#!/bin/bash

set -euo pipefail

# Add every file from command-line arguments
git add "$@"

# Prompt for commit message
read -e -r -p "Commit: " MESSAGE

# Commit and push
git commit -m "$MESSAGE"
git push
