#!/bin/bash
name=TEST.md
username=$(git config user.name)
repository=$(pwd | rev | cut -d/ -f2 | rev)
directory=$(pwd | rev | cut -d/ -f1 | rev)
echo -e $(echo "## ${directory^^}\n" | tr "_" " ") > $name
echo -n "Description: "
read string
echo -e "$string\n" >> $name
for file in $(ls | grep -Ev "README|TEST|main." | sort -g) ; do
	echo -e "* [$file](https://github.com/$username/$repository/tree/main/$directory/$file)\n" >> $name
done
