#!/bin/bash

NAME=TEST.md
USERNAME=$(git config user.name)

REPOSITORY=$(pwd | rev | cut -d/ -f2 | rev)
DIRECTORY=$(pwd | rev | cut -d/ -f1 | rev)

HEADING=$(echo "$DIRECTORY" | tr '_' ' ' | sed 's/-/ - /g' | sed 's/\b\(.\)/\u\1/g')

echo -e $(echo "## ${HEADING}\n" | tr "_" " ") > $NAME
read -e -r -p "Description: " STRING
echo -e "$STRING" >> $NAME

for FILE in *; do
	echo -e "\n* [$FILE](https://github.com/$USERNAME/$REPOSITORY/tree/main/$DIRECTORY/$FILE)" >> $NAME
done
